"""Initial

Revision ID: d048575b0aaf
Revises: 
Create Date: 2025-01-09 09:20:13.223207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd048575b0aaf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spimex_trading_results',
    sa.Column('exchange_product_id', sa.String(length=255), nullable=False, comment='Unique identifier for the exchange product.'),
    sa.Column('exchange_product_name', sa.String(length=255), nullable=False, comment='Full name of the exchange product.'),
    sa.Column('oil_id', sa.String(length=4), nullable=False, comment='4-character identifier for the oil type'),
    sa.Column('delivery_basis_id', sa.String(length=3), nullable=False, comment='3-character code for delivery basis'),
    sa.Column('delivery_basis_name', sa.String(length=255), nullable=False, comment='Full name of the delivery basis location.'),
    sa.Column('delivery_type_id', sa.String(length=1), nullable=False, comment='Single character identifying delivery type'),
    sa.Column('volume', sa.Integer(), nullable=False, comment='Total trading volume for the product.'),
    sa.Column('total', sa.Integer(), nullable=False, comment='Total monetary value of test_trades'),
    sa.Column('count', sa.Integer(), nullable=False, comment='Number of test_trades executed'),
    sa.Column('date', sa.Date(), nullable=False, comment='Date of the trading results'),
    sa.Column('created_on', sa.DateTime(), nullable=False, comment='Record creation timestamp, auto-set to now'),
    sa.Column('updated_on', sa.DateTime(), nullable=False, comment='Last update timestamp, auto-set to now'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='The numeric primary key for the model.'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spimex_trading_results')
    # ### end Alembic commands ###
